# Generated by Django 5.2 on 2025-05-26 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0003_categoria_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alquiler',
            name='evento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='pagoalquiler',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('qr', 'QR')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Evento',
        ),
    ]
