# Generated by Django 5.2 on 2025-05-29 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0004_alter_alquiler_evento_alter_categoria_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traje',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='trajes/'),
        ),
    ]
