# Generated by Django 5.2 on 2025-06-05 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0005_traje_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelo3d',
            name='traje',
        ),
        migrations.AddField(
            model_name='traje',
            name='modelo_3d_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='categoria/'),
        ),
        migrations.DeleteModel(
            name='ImagenTraje',
        ),
        migrations.DeleteModel(
            name='Modelo3D',
        ),
    ]
