# Generated by Django 5.2 on 2025-06-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0006_remove_modelo3d_traje_traje_modelo_3d_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alquiler',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
