# Generated by Django 5.2 on 2025-06-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0007_alquiler_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alquiler',
            name='estado',
            field=models.CharField(choices=[('reservado', 'Reservado'), ('activo', 'Activo'), ('devuelto', 'Devuelto'), ('cancelado', 'Cancelado'), ('alquilado', 'Alquilado')], default='reservado', max_length=10),
        ),
    ]
