# Generated by Django 5.2 on 2025-06-10 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0009_alter_categoria_options_remove_categoria_imagen_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.AddField(
            model_name='usuario',
            name='uid',
            field=models.CharField(default='default-uid', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
