# Generated by Django 5.2 on 2025-06-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0010_delete_categoria_usuario_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='alquiler',
            name='talla',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='alquiler',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia Bancaria'), ('qr', 'Código QR')], default='efectivo', max_length=15),
        ),
        migrations.AlterField(
            model_name='alquiler',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='celular',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
